In [72]:
import pandas as pd
import random as rnd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [73]:
train_df = pd.read_csv('../datasets/water_table/water_table_train_values.csv')
label_df = pd.read_csv('../datasets/water_table/water_table_train_label.csv')

In [74]:
train_df

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434,Mashine,0,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573,Mshoro,0,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464,Kwa Mzee Lugawa,0,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [75]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  object
 3   funder                 55765 non-null  object
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  object
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59400 non-null  object
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  object
 11  subvillage             59029 non-null  object
 12  region                 59400 non-null  object
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  object
 16  ward                   59400 non-null  object
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  object
 20  scheme_management      55523 non-null  object
 21  scheme_name            31234 non-null  object
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  object
 25  extraction_type_group  59400 non-null  object
 26  extraction_type_class  59400 non-null  object
 27  management             59400 non-null  object
 28  management_group       59400 non-null  object
 29  payment                59400 non-null  object
 30  payment_type           59400 non-null  object
 31  water_quality          59400 non-null  object
 32  quality_group          59400 non-null  object
 33  quantity               59400 non-null  object
 34  quantity_group         59400 non-null  object
 35  source                 59400 non-null  object
 36  source_type            59400 non-null  object
 37  source_class           59400 non-null  object
 38  waterpoint_type        59400 non-null  object
 39  waterpoint_type_group  59400 non-null  object
dtypes: float64(3), int64(7), object(30)
memory usage: 18.1+ MB

In [76]:
train_df['water_quality'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
59395    False
59396    False
59397    False
59398    False
59399    False
Name: water_quality, Length: 59400, dtype: bool

In [77]:
#counting null values

train_df.apply(lambda x: sum(x.isnull()))

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

In [78]:
#counting unique values in those columns with null values
print("df.funder", train_df['funder'].unique(), train_df['funder'].unique().shape)
print("df.installer", train_df['installer'].unique(), train_df['installer'].unique().shape)
print("df.subvillage", train_df['subvillage'].unique(), train_df['subvillage'].unique().shape)
print("df.public_meeting", train_df['public_meeting'].unique(), train_df['public_meeting'].unique().shape)
print("df.scheme_management", train_df['scheme_management'].unique(), train_df['scheme_management'].unique().shape)
print("df.scheme_name", train_df['scheme_name'].unique(), train_df['scheme_name'].unique().shape)
print("df.permit", train_df['permit'].unique(), train_df['permit'].unique().shape)

df.funder ['Roman' 'Grumeti' 'Lottery Club' ... 'Dina' 'Brown' 'Samlo'] (1898,)
df.installer ['Roman' 'GRUMETI' 'World vision' ... 'Dina' 'brown' 'SELEPTA'] (2146,)
df.subvillage ['Mnyusi B' 'Nyamara' 'Majengo' ... 'Itete B' 'Maore Kati' 'Kikatanyemba'] (19288,)
df.public_meeting [True nan False] (3,)
df.scheme_management ['VWC' 'Other' nan 'Private operator' 'WUG' 'Water Board' 'WUA'
 'Water authority' 'Company' 'Parastatal' 'Trust' 'SWC' 'None'] (13,)
df.scheme_name ['Roman' nan 'Nyumba ya mungu pipe scheme' ... 'BL Nsherehehe'
 'Magati  gravity spri' 'Mtawanya'] (2697,)
df.permit [False True nan] (3,)

In [79]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
# creating initial dataframe
bridge_types = ('Arch','Beam','Truss','Cantilever','Tied Arch','Suspension','Cable')
bridge_df = pd.DataFrame(bridge_types, columns=['Bridge_Types'])
# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column
bridge_df['Bridge_Types_Cat'] = labelencoder.fit_transform(bridge_df['Bridge_Types'])
bridge_df

  Bridge_Types  Bridge_Types_Cat
0         Arch                 0
1         Beam                 1
2        Truss                 6
3   Cantilever                 3
4    Tied Arch                 5
5   Suspension                 4
6        Cable                 2

In [80]:
#remove all columns with null for simplicity
train_df2 = pd.read_csv('../datasets/water_table/water_table_train_values.csv')
train_df2 = train_df2.drop('funder', axis = 1)
train_df2 = train_df2.drop('installer', axis = 1)
train_df2 = train_df2.drop('subvillage', axis = 1)
train_df2 = train_df2.drop('public_meeting', axis = 1)
train_df2 = train_df2.drop('scheme_management', axis = 1)
train_df2 = train_df2.drop('scheme_name', axis = 1)
train_df2 = train_df2.drop('permit', axis = 1)

In [93]:
#we're gonna one hot encode those columns with "object" datatype
type_dict = train_df2.dtypes.to_dict()

for name, dtype in type_dict.items():
    if(dtype=='object'):
        print(name)

date_recorded
wpt_name
basin
region
lga
ward
recorded_by
extraction_type
extraction_type_group
extraction_type_class
management
management_group
payment
payment_type
water_quality
quality_group
quantity
quantity_group
source
source_type
source_class
waterpoint_type
waterpoint_type_group

In [89]:
type_dict

{'id': dtype('int64'),
 'amount_tsh': dtype('float64'),
 'date_recorded': dtype('O'),
 'gps_height': dtype('int64'),
 'longitude': dtype('float64'),
 'latitude': dtype('float64'),
 'wpt_name': dtype('O'),
 'num_private': dtype('int64'),
 'basin': dtype('O'),
 'region': dtype('O'),
 'region_code': dtype('int64'),
 'district_code': dtype('int64'),
 'lga': dtype('O'),
 'ward': dtype('O'),
 'population': dtype('int64'),
 'recorded_by': dtype('O'),
 'construction_year': dtype('int64'),
 'extraction_type': dtype('O'),
 'extraction_type_group': dtype('O'),
 'extraction_type_class': dtype('O'),
 'management': dtype('O'),
 'management_group': dtype('O'),
 'payment': dtype('O'),
 'payment_type': dtype('O'),
 'water_quality': dtype('O'),
 'quality_group': dtype('O'),
 'quantity': dtype('O'),
 'quantity_group': dtype('O'),
 'source': dtype('O'),
 'source_type': dtype('O'),
 'source_class': dtype('O'),
 'waterpoint_type': dtype('O'),
 'waterpoint_type_group': dtype('O')}

In [82]:
train_df2

,id,amount_tsh,date_recorded,gps_height,longitude,latitude,wpt_name,num_private,basin,region,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,1390,34.938093,-9.856322,none,0,Lake Nyasa,Iringa,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,1399,34.698766,-2.147466,Zahanati,0,Lake Victoria,Mara,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,686,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Manyara,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,263,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mtwara,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,0,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kagera,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59395,60739,10.0,2013-05-03,1210,37.169807,-3.253847,Area Three Namba 27,0,Pangani,Kilimanjaro,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,1212,35.249991,-9.070629,Kwa Yahona Kuvala,0,Rufiji,Iringa,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,0,34.017087,-8.750434,Mashine,0,Rufiji,Mbeya,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,0,35.861315,-6.378573,Mshoro,0,Rufiji,Dodoma,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,191,38.104048,-6.747464,Kwa Mzee Lugawa,0,Wami / Ruvu,Morogoro,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

train_df2['region'].unique()
labelencoder = LabelEncoder()
train_df2['region_cat'] = labelencoder.fit_transform(train_df2['region'])

In [83]:
train_df2.region_cat.unique()

AttributeError: 'DataFrame' object has no attribute 'region_cat'